version: "2"
services:
  db:
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    links:
      - db:db
    ports:
      - "8080:80"